### ISSUE TITLE
Host container integration

### ISSUE THREAD

**Issue by zmrow** [bottlerocket-os/bottlerocket#229]
This issue tracks the pieces necessary to integrate host containers into Thar.  

- [x] Host container puller/starter (@etungsten) - this Go binary interacts with containerd to pull and start containers - #219 .  Implemented in #222 
- [x] servicedog (@zmrow) This Rust binary acts as the `restart-command` for these host containers (but is generic enough to serve other purposes) and manipulates the systemd units to start/stop containers. - #218 . Implemented in #232 
- [x] Unit file templates / default settings (@zmrow)  This is the final step and ties all the pieces together. Adds the unit file templates and required settings and metadata for the host containers. Implemented in #243
