### ISSUE TITLE
v1.13.0 🎺 tracking issue

### ISSUE THREAD

**Issue by jpmcb** [bottlerocket-os/bottlerocket#2760]
Hello! This is a _"living"_ issue used to track bug fixes, features, and things landing in the next release of Bottlerocket; v1.13.0.

This is a convenient way for the maintainers and the community to have a birds eye view of what's happening in any given Bottlerocket release. You'll find things we're targeting for the release, target dates, and important maintenance tasks.

But [**_anything is subject to change_**](https://github.com/bottlerocket-os/bottlerocket/blob/develop/CODE_OF_CONDUCT.md), _**this isn't a guarantee**_ anything will _actually_ land in a given release, and this tracking issue is not all encompassing. For a full comparison of new things for this release, use [the GitHub `/compare` feature](https://github.com/bottlerocket-os/bottlerocket/compare/) and check the differences between the `1.12.x` branch and `develop` (the latest changes that will eventually land in the `1.13.x` branch).

---

### Release captains 🧑‍✈️ 

@jpmcb & @stmcginnis 

### Targeting 🎯 
- [x] https://github.com/bottlerocket-os/bottlerocket/issues/1079
- [ ] ~https://github.com/bottlerocket-os/bottlerocket/issues/2501~
- [x] https://github.com/bottlerocket-os/bottlerocket/issues/2504
- [x] https://github.com/bottlerocket-os/bottlerocket/issues/2758
- [x] https://github.com/bottlerocket-os/bottlerocket/issues/2633
- [x] https://github.com/bottlerocket-os/bottlerocket/issues/2770
- [x] https://github.com/bottlerocket-os/bottlerocket/issues/2843
- [x] https://github.com/bottlerocket-os/bottlerocket/pull/2850
### Done! ✅ 

_It's quiet here. Too quiet ..._

### Maintenance 🔧 

- [x] #2768
- [x] #2762
- [x] #2763
- [x] #2764
- [x] #2761
- [x] #2765
- [x] #2766
- [x] #2767

**Comment by bcressey** [comment]
The Secure Boot feature is going through some additional review and testing so it won't make it in 1.13.0.

**Comment by stmcginnis** [comment]
Just to call out here for increased visibility - the 1.13.0 release will also [no longer ship the Kubernetes 1.21 variants](https://github.com/bottlerocket-os/bottlerocket/issues/2633).
