### ISSUE TITLE
Re-implement Bottlerocket template system for Out-of-tree Builds

### ISSUE THREAD

**Issue by cbgbt** [bottlerocket-os/bottlerocket#3133]
Related to #2669

**What I'd Like**:
We need to be able to express settings dependencies for templates as described by the design document in #2834. This would allow the settings system to determine what settings and at what versions the API should render templates.

As an example, a template might look something like this:

```
[required-extensions]
motd = { version = "v1', helpers = ["boldface"] }
+++
Today's motd is {{ settings.motd }}

Let's pretend that the `motd` extension gives us a custom helper for boldfacing text {{ boldface "like this" }}.
```

Where the settings required are specified in a header called "frontmatter" and the template body is given as a string below.

To do:
* [x] Implement template parser (#3284)
* [x] Implement template renderer (#3302)
* [x] Implement settings generator binary (#3316)
* [x] Migrate `thar-be-settings` and existing config templates to the new renderer library (https://github.com/bottlerocket-os/bottlerocket/pull/3346)
* [x] Migrate `sundog` and settings-generators to the new binary (#3316)
* [ ] Replace [`ReplaceTemplateMigration`](https://github.com/bottlerocket-os/bottlerocket/blob/ef2fe106efd55728596c0d89cbfce53a58f79e61/sources/api/migration/migration-helpers/src/common_migrations.rs#L522)
* [x] Write a migration guide to help users port existing templates (#3488)
