### ISSUE TITLE
v1.15.0 🦒 Tracking Issue

### ISSUE THREAD

**Issue by stmcginnis** [bottlerocket-os/bottlerocket#3169]
This is a _"living"_ issue used to track bug fixes, features, and things landing in the next release of Bottlerocket v1.15.0.

This is a convenient way for the maintainers and the community to have a birds eye view of what's happening in any given Bottlerocket release. You'll find things we're targeting for the release, target dates, and important maintenance tasks.

But [**_anything is subject to change_**](https://github.com/bottlerocket-os/bottlerocket/blob/develop/CODE_OF_CONDUCT.md), _**this isn't a guarantee**_ anything will _actually_ land in a given release, and this tracking issue is not all encompassing. For a full comparison of new things for this release, use [the GitHub `/compare` feature](https://github.com/bottlerocket-os/bottlerocket/compare/) and check the differences between the `1.14.x` branch and `develop` (the latest changes that will eventually land in the `1.15.x` branch).

**Note:** We're stretching the interval until 1.15 to make up for lost time during the 1.13.x release parade and to deliver larger features that can't easily be subdivided. Once everything has been scoped, we'll have a more accurate date and details. Targeting very early September, 2023, but again, this is subject to change.

---

### Release captains 🧑‍✈️ 

TBD

### Targeting 🎯 

- [x] https://github.com/bottlerocket-os/bottlerocket/issues/2501
- [x] #2731
- [x] #2852
- [x] https://github.com/bottlerocket-os/bottlerocket/issues/2164
- [x] https://github.com/bottlerocket-os/bottlerocket/issues/3274
- [x] https://github.com/bottlerocket-os/bottlerocket/issues/2844
- [x] https://github.com/bottlerocket-os/bottlerocket/issues/3036
- [x] https://github.com/bottlerocket-os/bottlerocket/issues/2759

### Maintenance 🔧 

- [x] #3170
- [x] #3171
- [x] #3172
- [x] #3173
- [x] #3174
- [x] #3325
