### ISSUE TITLE
v1.14.2 Tracking Issue 🐞

### ISSUE THREAD

**Issue by stmcginnis** [bottlerocket-os/bottlerocket#3210]
This is a _"living"_ issue used to track bug fixes and things landing in the next release point release of Bottlerocket v1.14.2.

This is a convenient way for the maintainers and the community to have a birds eye view of what's happening in any given Bottlerocket release. You'll find things we're targeting for the release, target dates, and important maintenance tasks.

But [**_anything is subject to change_**](https://github.com/bottlerocket-os/bottlerocket/blob/develop/CODE_OF_CONDUCT.md), _**this isn't a guarantee**_ anything will _actually_ land in a given release, and this tracking issue is not all encompassing. For a full comparison of new things for this release, use [the GitHub `/compare` feature](https://github.com/bottlerocket-os/bottlerocket/compare/) and check the differences between the `1.14.x` branch and `v1.14.1` tag.

---

### Release captains 🧑‍✈️ 

@etungsten and @stmcginnis 

### Targeting 🎯 

- [x] https://github.com/bottlerocket-os/bottlerocket/issues/3167
- [x] https://github.com/bottlerocket-os/bottlerocket/issues/3143
- [x] https://github.com/bottlerocket-os/bottlerocket/pull/3224
- [x] https://github.com/bottlerocket-os/bottlerocket/issues/3230

### Maintenance 🔧 

- [x] https://github.com/bottlerocket-os/bottlerocket/pull/3225
- [x] https://github.com/bottlerocket-os/bottlerocket/pull/3241

**Comment by stmcginnis** [comment]
The [v1.14.2 release](https://github.com/bottlerocket-os/bottlerocket/releases/tag/v1.14.2) is now available.
