### ISSUE TITLE
v1.16.0 🎠 Tracking Issue

### ISSUE THREAD

**Issue by stmcginnis** [bottlerocket-os/bottlerocket#3469]
This is a _"living"_ issue used to track bug fixes, features, and things landing in the next release of Bottlerocket v1.16.0.

This is a convenient way for the maintainers and the community to have a birds eye view of what's happening in any given Bottlerocket release. You'll find things we're targeting for the release, target dates, and important maintenance tasks.

But [**_anything is subject to change_**](https://github.com/bottlerocket-os/bottlerocket/blob/develop/CODE_OF_CONDUCT.md), _**this isn't a guarantee**_ anything will _actually_ land in a given release, and this tracking issue is not all encompassing. For a full comparison of new things for this release, use [the GitHub `/compare` feature](https://github.com/bottlerocket-os/bottlerocket/compare/) and check the differences between the `1.15.x` branch and `develop` (the latest changes that will eventually land in the `1.16.x` branch).

---

### Release captains 🧑‍✈️ 

@rpkelly 

### Targeting 🎯 

- [x] #3511
- [x] https://github.com/bottlerocket-os/bottlerocket/pull/3540
- [x] https://github.com/bottlerocket-os/bottlerocket/pull/3444
- [x] https://github.com/bottlerocket-os/bottlerocket/pull/3509
- [x] https://github.com/bottlerocket-os/bottlerocket/pull/3528
- [x] https://github.com/bottlerocket-os/bottlerocket/pull/3520

### Maintenance 🔧 

- [x] #3470
- [x] #3471
- [x] #3472
- [x] #3473
- [x] #3474
- [x] #3475

**Comment by gthao313** [comment]
v1.16.0 has been released on 10/30/2023
