### ISSUE TITLE
OOTB: Port existing settings models to Settings Extensions

### ISSUE THREAD

**Issue by cbgbt** [bottlerocket-os/bottlerocket#3614]
This serves as a tracking issue for the effort to port all settings models to settings extensions.

As per the [settings extension design](https://github.com/bottlerocket-os/bottlerocket/blob/b375585ce32e61a2d796a1f9eff9d374964fa813/docs/design/settings/extensions/modular-settings-extensions.md), existing settings models must be ported to installable settings extensions.

For each model, this involves:
* Creating an extension that encapsulates the behavior of the model using the [settings SDK](https://github.com/bottlerocket-os/bottlerocket-settings-sdk/)
* Replacing the current model with a library reference to the new extension
* Creating an RPM package that can install the settings extension binary

Includes
- [x] bottlerocket-os/bottlerocket#3649 
- [x] bottlerocket-os/bottlerocket#3650 
- [x] bottlerocket-os/bottlerocket#3651 
- [x] bottlerocket-os/bottlerocket#3652 
- [x] bottlerocket-os/bottlerocket#3653 
- [ ] bottlerocket-os/bottlerocket-settings-sdk#75 
- [x] bottlerocket-os/bottlerocket#3655 
- [x] bottlerocket-os/bottlerocket#3656 
- [x] bottlerocket-os/bottlerocket#3657 
- [x] bottlerocket-os/bottlerocket#3658 
- [x] bottlerocket-os/bottlerocket#3659 
- [x] bottlerocket-os/bottlerocket#3660 
- [x] bottlerocket-os/bottlerocket#3661 
- [x] bottlerocket-os/bottlerocket#3662 
- [x] bottlerocket-os/bottlerocket#3663 
- [x] bottlerocket-os/bottlerocket#3664 
- [x] bottlerocket-os/bottlerocket#3665 
- [x] bottlerocket-os/bottlerocket#3666

**Comment by webern** [comment]
This is a tracking issue that shouldn't be closed until all of the sub-tasks are done. Re-opening.

**Comment by bcressey** [comment]
Resolving this since https://github.com/bottlerocket-os/bottlerocket-settings-sdk/issues/75 is the only open issue.
