### ISSUE TITLE
v1.18.0 🫎 Tracking Issue

### ISSUE THREAD

**Issue by stockholmux** [bottlerocket-os/bottlerocket#3688]
This is a "_living_" issue used to track bug fixes, features, and things landing in the next release of Bottlerocket v1.18.0.

This is a convenient way for the maintainers and the community to have a birds eye view of what's happening in any given Bottlerocket release. You'll find things we're targeting for the release, target dates, and important maintenance tasks.

But **[anything is subject to change](https://github.com/bottlerocket-os/bottlerocket/blob/develop/CODE_OF_CONDUCT.md), this isn't a guarantee** anything will actually land in a given release, and this tracking issue is not all encompassing. For a full comparison of new things for this release, use [the GitHub /compare feature](https://github.com/bottlerocket-os/bottlerocket/compare/) and check the differences between the `1.17.x` branch and `develop` (the latest changes that will eventually land in the `1.18.x` branch).

---

## v1.18.0 🫎
**Release captains 🧑‍✈️**

@jpculp @ginglis13 

**Targeting 🎯**

- [x] https://github.com/bottlerocket-os/bottlerocket/pull/3628
- [x] https://github.com/bottlerocket-os/bottlerocket/pull/3674
- [x] https://github.com/bottlerocket-os/bottlerocket/pull/3680
- [x] https://github.com/bottlerocket-os/bottlerocket/pull/3686
- [x] https://github.com/bottlerocket-os/bottlerocket/pull/3689
- [x] https://github.com/bottlerocket-os/bottlerocket/pull/3690

**Bug Fixes :lady_beetle:**

- [x] #3691 

**Maintenance 🔧**

- [x] https://github.com/bottlerocket-os/bottlerocket/pull/3692
- [x] https://github.com/bottlerocket-os/bottlerocket/pull/3687
- [x] https://github.com/bottlerocket-os/bottlerocket/pull/3704
- [x] https://github.com/bottlerocket-os/bottlerocket/issues/3694

**Comment by ginglis13** [comment]
[v1.18.0 has been released](https://github.com/bottlerocket-os/bottlerocket/releases/tag/v1.18.0)
