### ISSUE TITLE
 v1.19.0 🦍 Tracking Issue

### ISSUE THREAD

**Issue by ginglis13** [bottlerocket-os/bottlerocket#3731]
This is a "_living_" issue used to track bug fixes, features, and things landing in the next release of Bottlerocket v1.19.0.

This is a convenient way for the maintainers and the community to have a birds eye view of what's happening in any given Bottlerocket release. You'll find things we're targeting for the release, target dates, and important maintenance tasks.

But **[anything is subject to change](https://github.com/bottlerocket-os/bottlerocket/blob/develop/CODE_OF_CONDUCT.md), this isn't a guarantee** anything will actually land in a given release, and this tracking issue is not all encompassing. For a full comparison of new things for this release, use [the GitHub /compare feature](https://github.com/bottlerocket-os/bottlerocket/compare/) and check the differences between the `1.18.x` branch and `develop` (the latest changes that will eventually land in the `1.19.x` branch).

---

## v1.19.0 🦍 
**Release captains 🧑‍✈️**

@yeazelm @vyaghras 

**Targeting 🎯**

- [x] #3727 
- [x] #3730 
- [x] #3734

**Bug Fixes :lady_beetle:**

- [x] #3720 

**Maintenance 🔧**

- [x] https://github.com/bottlerocket-os/bottlerocket/pull/3722
- [x] https://github.com/bottlerocket-os/bottlerocket/issues/3729
- [x] https://github.com/bottlerocket-os/bottlerocket/issues/3736
- [x] https://github.com/bottlerocket-os/bottlerocket/issues/3737
- [x] https://github.com/bottlerocket-os/bottlerocket/issues/3739

**Comment by yeazelm** [comment]
Bottlerocket 1.19.0 is released! https://github.com/bottlerocket-os/bottlerocket/releases/tag/v1.19.0
