### ISSUE TITLE
Kubernetes-1.30 package and variants Tracking Issue 🐳 

### ISSUE THREAD

**Issue by ginglis13** [bottlerocket-os/bottlerocket#3862]
This is a "living" issue used to track features, bug fixes, and work required for Bottlerocket k8s-1.30 variants.

Tracking ticket for completing the work required to add package(s) and variants required for kubernetes 1.30.

**What I'd like:**

- [x] #3859 
- [x] Add ecr-credential-provider-1.30 package #3936 
- [x] Use k8s 1.30 sources in package kubernetes-1.30 #3936 
- [x] https://github.com/bottlerocket-os/bottlerocket-sdk/pull/178
