### ISSUE TITLE
v1.20.0 🐫  Tracking Issue

### ISSUE THREAD

**Issue by ginglis13** [bottlerocket-os/bottlerocket#3942]
This is a "_living_" issue used to track bug fixes, features, and things landing in the next release of Bottlerocket v1.20.0.

This is a convenient way for the maintainers and the community to have a birds eye view of what's happening in any given Bottlerocket release. You'll find things we're targeting for the release, target dates, and important maintenance tasks.

But **[anything is subject to change](https://github.com/bottlerocket-os/bottlerocket/blob/develop/CODE_OF_CONDUCT.md), this isn't a guarantee** anything will actually land in a given release, and this tracking issue is not all encompassing. For a full comparison of new things for this release, use [the GitHub /compare feature](https://github.com/bottlerocket-os/bottlerocket/compare/) and check the differences between the `1.19.x` branch and `develop`.

---

## v1.20.0 🐫  
**Release captains 🧑‍✈️**
@rpkelly @ginglis13 

**Targeting 🎯**

- [x] Kubernetes 1.30 support #3862
- [x] #3873 
- [x] #3945
- [x] #3907
- [x] #3886
- [x] #3852
- [x] #3829
- [x] #3834

**Bug Fixes :lady_beetle:**

**Maintenance 🔧**

- [x] https://github.com/bottlerocket-os/bottlerocket/pull/3934
- [x] https://github.com/bottlerocket-os/bottlerocket/pull/3930
- [x] https://github.com/bottlerocket-os/bottlerocket/pull/3938
- [x] #3939
- [x] #3943
- [x] #3950

**Comment by yeazelm** [comment]
1.20.0 is released! https://github.com/bottlerocket-os/bottlerocket/releases/tag/v1.20.0
