### ISSUE TITLE
v1.20.1 🐫  Tracking Issue 

### ISSUE THREAD

**Issue by yeazelm** [bottlerocket-os/bottlerocket#4025]
This is a "living" issue used to track bug fixes, features, and things landing in the next release of Bottlerocket v1.20.0.

This is a convenient way for the maintainers and the community to have a birds eye view of what's happening in any given Bottlerocket release. You'll find things we're targeting for the release, target dates, and important maintenance tasks.

But [anything is subject to change](https://github.com/bottlerocket-os/bottlerocket/blob/develop/CODE_OF_CONDUCT.md), this isn't a guarantee anything will actually land in a given release, and this tracking issue is not all encompassing. For a full comparison of new things for this release, use [the GitHub /compare feature](https://github.com/bottlerocket-os/bottlerocket/compare/) and check the differences between the 1.20.x branch and develop.

---

## v1.20.0 🐫  
**Release captains 🧑‍✈️**
@rpkelly @yeazelm @larvacea 

Targeting 🎯

Bug Fixes 🐞

- [x] https://github.com/bottlerocket-os/bottlerocket/pull/3981
- [x] ~https://github.com/bottlerocket-os/bottlerocket/pull/4007~ We pulled this from the release due to problems discussed in https://github.com/bottlerocket-os/bottlerocket/pull/4026

Maintenance 🔧
- [x] https://github.com/bottlerocket-os/bottlerocket/pull/3976
- [x] https://github.com/bottlerocket-os/bottlerocket/pull/3972
- [x] https://github.com/bottlerocket-os/bottlerocket/pull/4029

**Comment by misterek** [comment]
Did this get released?  We are seeing some Bottlerocket OS 1.20.1 (aws-k8s-1.29) , but I don't see it in the release page.

**Comment by yeazelm** [comment]
@misterek we are in the middle of the release, sorry for the confusing state but we will have the release on GitHub very shortly!

**Comment by yeazelm** [comment]
We released v1.20.1! Please see the release notes: https://github.com/bottlerocket-os/bottlerocket/releases/tag/v1.20.1
