### ISSUE TITLE
v1.20.5 🐫  Tracking Issue

### ISSUE THREAD

**Issue by ginglis13** [bottlerocket-os/bottlerocket#4107]
This is a "living" issue used to track bug fixes, features, and things landing in the next release of Bottlerocket v1.20.5.

This is a convenient way for the maintainers and the community to have a birds eye view of what's happening in any given Bottlerocket release. You'll find things we're targeting for the release, target dates, and important maintenance tasks.

But [anything is subject to change](https://github.com/bottlerocket-os/bottlerocket/blob/develop/CODE_OF_CONDUCT.md), this isn't a guarantee anything will actually land in a given release, and this tracking issue is not all encompassing. For a full comparison of new things for this release, use [the GitHub /compare feature](https://github.com/bottlerocket-os/bottlerocket/compare/) and check the differences between the 1.20.x branch and develop.

---

## v1.20.5 🐫 
**Release captains 🧑‍✈️**
@KCSesh @ginglis13 @tquirk-aws @sam-berning 

Targeting 🎯
 N/A

Bug Fixes 🐞

N/A

Maintenance 🔧
- [x] https://github.com/bottlerocket-os/bottlerocket/pull/4104
- [x] https://github.com/bottlerocket-os/bottlerocket/pull/4113
- [x] https://github.com/bottlerocket-os/bottlerocket/pull/4111
- [x] https://github.com/bottlerocket-os/bottlerocket/pull/4108
- [x] https://github.com/bottlerocket-os/bottlerocket/pull/4110

**Comment by misterek** [comment]
I know I harp on this every release, and I apologize.  Is the intention that this tracking issue is closed before or after the new AMI starts getting picked up by karpenter?  We started seeing 1.20.5 around 30 minutes ago.

**Comment by hamza-faethm** [comment]
> I know I harp on this every release, and I apologize. Is the intention that this tracking issue is closed before or after the new AMI starts getting picked up by karpenter? We started seeing 1.20.5 around 30 minutes ago.

Echoing misterek, we are also seeing 1.20.5 but no release tag exists. Is this expected?

❯ aws ssm get-parameter --name /aws/service/bottlerocket/aws-k8s-1.29/x86_64/latest/image_version --region ap-southeast-2 --query "Parameter.Value" --output text --no-cli-pager

`1.20.5-a3e8bda1`

**Comment by misterek** [comment]
It was just released. About an hour after we started seeing nodes being updated: https://github.com/bottlerocket-os/bottlerocket/releases/tag/v1.20.5

**Comment by rpkelly** [comment]
We have just completed release activities for 1.20.5. Apologies, there was every intention to post prior to the release starting, but a miscommunication led to that not being communicated with the engineer actually running the release. We will exam our procedures and endeavor to improve in the future

**Comment by misterek** [comment]
Thanks.  My personal strong preference is to have the github release published _before_ the AMi is seen by Karpenter.

That being said, I understand there may be a desire not to do this.  In this case, these activities were going on at the same time as a us-east-1 outage, so there was some confusion/concern as far as why nodes were getting replaced for awhile.

**Comment by ytsssun** [comment]
All tasks for v1.20.5 release is done. Closing this issue.
