### ISSUE TITLE
v1.21.0 🪁  Tracking Issue 

### ISSUE THREAD

**Issue by yeazelm** [bottlerocket-os/bottlerocket#4121]
This is a "living" issue used to track bug fixes, features, and things landing in the next release of Bottlerocket v1.21.0.

This is a convenient way for the maintainers and the community to have a birds eye view of what's happening in any given Bottlerocket release. You'll find things we're targeting for the release, target dates, and important maintenance tasks.

But [anything is subject to change](https://github.com/bottlerocket-os/bottlerocket/blob/develop/CODE_OF_CONDUCT.md), this isn't a guarantee anything will actually land in a given release, and this tracking issue is not all encompassing. For a full comparison of new things for this release, use [the GitHub /compare feature](https://github.com/bottlerocket-os/bottlerocket/compare/) and check the differences between the 1.21.x branch and develop.

Release captains 🧑‍✈️
@rpkelly @gthao313 

Targeting 🎯
- [x] #3964 
- [x] drop k8s 1.27 and 1.28 support for metal and VMware #4079 and #4018
- [x] #3940 
- [x] #3984 
- [x] #4060 
- [x]  #3977 
- [x] #3982 
- [x] #4057 
- [x] #4038 
- [x] Enable settings extensions #4050 
- [x] #4118
- [x] Update to latest core-kit release 

Bug Fixes 🐞
N/A

Maintenance 🔧
- [x] #3999 
- [x] Update Twoliter  #4008 , #4086 , #4093 
- [x] #4117
- [x] #4099

**Comment by apexlnc** [comment]
Hey there @yeazelm, is there a target release date for 1.21.0? 

Super excited for this enhancement: https://github.com/bottlerocket-os/bottlerocket/pull/3977

🚀

**Comment by gthao313** [comment]
The 1.21.0 has passed validation and will be published shortly. AMIs are public and the SSM parameters should be available for this release or will be shortly. Watch for the release at https://github.com/bottlerocket-os/bottlerocket/releases to signal when the release is complete.

**Comment by misterek** [comment]
Thank you for announcing it here!

**Comment by gthao313** [comment]
The 1.21.0 is complete. Please see https://github.com/bottlerocket-os/bottlerocket/releases/v1.21.0 for more details.
