### ISSUE TITLE
Kubernetes 1.31 Variants Tracking Issue 👻 

### ISSUE THREAD

**Issue by ginglis13** [bottlerocket-os/bottlerocket#4137]
This is a "living" issue used to track features, bug fixes, and work required for Bottlerocket k8s-1.31 variants.

**What I'd like:**

- [x]  Add boilerplate packages for k8s 1.31 (bottlerocket-core-kit) https://github.com/bottlerocket-os/bottlerocket-core-kit/pull/81
- [x] Add boilerplate variants for k8s 1.31 (bottlerocket) https://github.com/bottlerocket-os/bottlerocket/pull/4142
- [x] Use k8s 1.31 sources in packages kubernetes-1.31 and ecr-credential-provider-1.31 https://github.com/bottlerocket-os/bottlerocket-core-kit/pull/117

**Comment by ginglis13** [comment]
We've released k8s-1.31 variants in Bottlerocket 1.22.0 https://github.com/bottlerocket-os/bottlerocket/releases/tag/v1.22.0
