### ISSUE TITLE
v1.21.1 🪁 Tracking Issue

### ISSUE THREAD

**Issue by ginglis13** [bottlerocket-os/bottlerocket#4148]
This is a "living" issue used to track bug fixes, features, and things landing in the next release of Bottlerocket v1.21.1.

This is a convenient way for the maintainers and the community to have a birds eye view of what's happening in any given Bottlerocket release. You'll find things we're targeting for the release, target dates, and important maintenance tasks.

But [anything is subject to change](https://github.com/bottlerocket-os/bottlerocket/blob/develop/CODE_OF_CONDUCT.md), this isn't a guarantee anything will actually land in a given release, and this tracking issue is not all encompassing. For a full comparison of new things for this release, use [the GitHub /compare feature](https://github.com/bottlerocket-os/bottlerocket/compare/) and check the differences between the 1.21.x branch and develop.

Release captains 🧑‍✈️
@jpculp @ytsssun 

Targeting 🎯
N/A

Bug Fixes 🐞
- [ ] https://github.com/bottlerocket-os/bottlerocket/issues/4135 (addressed by #4145)

Maintenance 🔧
- [x] Update bottlerocket-core-kit to v2.3.3 (#4143, #4139)
- [x] Update bottlerocket-settings-models to v0.3.0 (#4145)
- [x] Use workspace dependencies for all dependencies (#4132)

**Comment by sam-berning** [comment]
The 1.21.1 has passed validation and will be published shortly. AMIs are public and the SSM parameters should be available for this release or will be shortly. Watch for the release at https://github.com/bottlerocket-os/bottlerocket/releases to signal when the release is complete.

**Comment by sam-berning** [comment]
Bottlerocket v1.21.1 has been released! 🚀 

Please see https://github.com/bottlerocket-os/bottlerocket/releases/v1.21.1 for more details.
