### ISSUE TITLE
v1.22.0 ⛰️  Tracking Issue

### ISSUE THREAD

**Issue by ginglis13** [bottlerocket-os/bottlerocket#4170]
This is a "living" issue used to track bug fixes, features, and things landing in the next release of Bottlerocket v1.22.0.

This is a convenient way for the maintainers and the community to have a birds eye view of what's happening in any given Bottlerocket release. You'll find things we're targeting for the release, target dates, and important maintenance tasks.

But [anything is subject to change](https://github.com/bottlerocket-os/bottlerocket/blob/develop/CODE_OF_CONDUCT.md), this isn't a guarantee anything will actually land in a given release, and this tracking issue is not all encompassing. For a full comparison of new things for this release, use [the GitHub /compare feature](https://github.com/bottlerocket-os/bottlerocket/compare/) and check the differences between the 1.22.x branch and develop.

Release captains 🧑‍✈️
@ginglis13 @mgsharm 

Targeting 🎯
- [x] Add Kubernetes 1.31 variants #4137
- [x] https://github.com/bottlerocket-os/bottlerocket-core-kit/pull/15
- [x] https://github.com/bottlerocket-os/bottlerocket-core-kit/pull/62

Maintenance 🔧
- [ ] https://github.com/bottlerocket-os/bottlerocket/pull/4177
- [x] https://github.com/bottlerocket-os/bottlerocket/pull/4171

**Comment by tquirk-aws** [comment]
The 1.22.0 has passed validation and will be published shortly. AMIs are public and the SSM parameters should be available for this release or will be shortly. Watch for the release at https://github.com/bottlerocket-os/bottlerocket/releases to signal when the release is complete.

**Comment by tquirk-aws** [comment]
Bottlerocket 1.22.0 has been released! 🚀

Please see https://github.com/bottlerocket-os/bottlerocket/releases/v1.22.0 for more details.
