### ISSUE TITLE
v1.23.0 🚎  Tracking Issue

### ISSUE THREAD

**Issue by yeazelm** [bottlerocket-os/bottlerocket#4190]
This is a "living" issue used to track bug fixes, features, and things landing in the next release of Bottlerocket v1.23.0.

This is a convenient way for the maintainers and the community to have a birds eye view of what's happening in any given Bottlerocket release. You'll find things we're targeting for the release, target dates, and important maintenance tasks.

But [anything is subject to change](https://github.com/bottlerocket-os/bottlerocket/blob/develop/CODE_OF_CONDUCT.md), this isn't a guarantee anything will actually land in a given release, and this tracking issue is not all encompassing. For a full comparison of new things for this release, use [the GitHub /compare feature](https://github.com/bottlerocket-os/bottlerocket/compare/) and check the differences between the 1.23.x branch and develop.

Release captains 🧑‍✈️
@yeazelm @arnaldo2792 

Targeting 🎯

- [X] Support Kubernetes NVIDIA Device Plugin configurations through API [#4182]
- [X] Support NVIDIA Container Toolkit configurations through API [#4182]
Maintenance 🔧
- [X] Update to bottlerocket-core-kit to v2.5.0 [#4189]

**Comment by rpkelly** [comment]
The 1.23.0 has passed validation and will be published shortly. AMIs are public and the SSM parameters should be available for this release or will be shortly. Watch for the release at https://github.com/bottlerocket-os/bottlerocket/releases to signal when the release is complete.

**Comment by rpkelly** [comment]
Bottlerocket 1.23.0 has been released! 🚀

Please see https://github.com/bottlerocket-os/bottlerocket/releases/v1.23.0 for more details.
