### ISSUE TITLE
v1.26.2 🎃 Tracking Issue

### ISSUE THREAD

**Issue by KCSesh** [bottlerocket-os/bottlerocket#4278]
This is a "living" issue used to track bug fixes, features, and things landing in the next release of Bottlerocket v1.26.0.

This is a convenient way for the maintainers and the community to have a birds eye view of what's happening in any given Bottlerocket release. You'll find things we're targeting for the release, target dates, and important maintenance tasks.

But [anything is subject to change](https://github.com/bottlerocket-os/bottlerocket/blob/develop/CODE_OF_CONDUCT.md), this isn't a guarantee anything will actually land in a given release, and this tracking issue is not all encompassing. For a full comparison of new things for this release, use [the GitHub /compare feature](https://github.com/bottlerocket-os/bottlerocket/compare/) and check the differences between the 1.24.x branch and develop.

Release captains 🧑‍✈️
@KCSesh @cbgbt @larvacea @sam-berning 

Maintenance 🔧
- [x] Update to bottlerocket-core-kit to v3.1.4
  - [x] bottlerocket-os/bottlerocket-core-kit#228 
  - [x] bottlerocket-os/bottlerocket-core-kit#231 
  - [x] bottlerocket-os/bottlerocket-core-kit#235

**Comment by sam-berning** [comment]
The 1.26.2 release has passed validation and will be published shortly. AMIs are public and the SSM parameters should be available for this release, or will be shortly. Watch for the release at https://github.com/bottlerocket-os/bottlerocket/releases to signal when the release is complete.

**Comment by ozancaglayan** [comment]
Hi. Is there a reason why the release is tagged as `pre-release` in github? Does this mean its still available through SSM channels and is just an issue with Github releases or is it still not fully released?

**Comment by sam-berning** [comment]
> Is there a reason why the release is tagged as `pre-release` in github?

In the past, we haven't removed the `pre-release` tag until we finished all release activities. For this release, we're trying out a longer wait time between publishing the images and updating the "latest" SSM parameters to point to the new version, which is why it's taken longer than usual for us to remove the `pre-release` tag.

The "latest" SSM parameters should be updated in all regions later today, but the AMIs and versioned SSM parameters for this version should be available now.

**Comment by sam-berning** [comment]
Bottlerocket 1.26.2 has been released! 🚀

Please see https://github.com/bottlerocket-os/bottlerocket/releases/v1.26.2 for more details.
