### ISSUE TITLE
Kubernetes 1.32 Variants Tracking Issue ⛄️

### ISSUE THREAD

**Issue by koooosh** [bottlerocket-os/bottlerocket#4318]
This is a "living" issue used to track features, bug fixes, and work required for Bottlerocket k8s-1.32 variants.

**What I'd like:**

- [x] Use beta sources in packages kubernetes-1.32 and ecr-credential-provider-1.32 (bottlerocket-core-kit)
- [x] Use official 1.32.0 sources in packages kubernetes-1.32 and ecr-credential-provider-1.32 (bottlerocket-core-kit) 
- [x] Add variants for k8s 1.32 (bottlerocket)

**Comment by koooosh** [comment]
K8s 1.32 variants released in v1.30: https://github.com/bottlerocket-os/bottlerocket/releases/tag/v1.30.0
