### ISSUE TITLE
Verify ARM64 support

### ISSUE THREAD

**Issue by tjkirch** [bottlerocket-os/bottlerocket#468]
Wherever EKS and ECR support ARM64, we should aim for the same level of support.

The [EKS ARM preview program](https://github.com/aws/containers-roadmap/tree/master/preview-programs/eks-arm-preview) provides images and ARM specific Kubernetes resources. We should use these resources and verify that we can successfully launch Bottlerocket nodes on ARM instances.

---

**Bottlerocket OS**

  * [x] Build and test Bottlerocket AMI ([booted](https://github.com/bottlerocket-os/bottlerocket/issues/468#issuecomment-580479388) and runs pods)
  
**Control container**

  * [x] Build and test control container for arm64 (supported in #694)
  
**Admin container**

  * [x] Build and test admin container for arm64 (supported in #694)
  
**Update operator**

  * [x] Build and test operator container for arm64 (supported in https://github.com/bottlerocket-os/bottlerocket-update-operator/pull/1)

**Kubernetes node**

  * [x] Build/configure and test node with CNI container for arm64 (supported in https://github.com/aws/amazon-vpc-cni-k8s/pull/837)

  * [x] Build/configure and test `pause` container for arm64 ([EKS preview provides a `pause-arm64` image](https://github.com/awslabs/amazon-eks-ami/blob/729dcb5f6dee3428e17c10b46c573c11802e4002/files/bootstrap.sh#L230))

**Comment by vielmetti** [comment]
Good to see this work underway - it's been 1+ month since the last specific comment here, is it possible to get an update?

**Comment by jahkeup** [comment]
We were able to verify that ARM builds of the OS, and other components, is possible and works:

* Bottlerocket OS - [provide `BUILDSYS_ARCH`](https://github.com/bottlerocket-os/bottlerocket/blob/dc4d498557a4b2a4d48d2998c2f0d933c9dff039/Makefile.toml#L5) when calling `cargo-make:` `cargo make --env BUILDSYS_ARCH=aarch64`
* [`bottlerocket-admin-container`](https://github.com/bottlerocket-os/bottlerocket-admin-container)  - [provide `ARCH=arm64` when calling `make`](https://github.com/bottlerocket-os/bottlerocket-admin-container/blob/f969cba3b0ff4f5da7d2bcc85101e7abe5ff6793/Makefile#L22): `make ARCH=arm64`
* [`bottlerocket-control-container`](https://github.com/bottlerocket-os/bottlerocket-control-container) - [provide `ARCH=arm64` when calling `make`](https://github.com/bottlerocket-os/bottlerocket-control-container/blob/baf204561e65a17af57ff5867ca9308775f142ca/Makefile#L22): `make ARCH=arm64`
* [`bottlerocket-update-operator`](https://github.com/bottlerocket-os/bottlerocket-update-operator) - [provide `ARCH=arm64` when calling `make`](https://github.com/bottlerocket-os/bottlerocket-update-operator/blob/7fcaf306d983df8542bb31bcad68a9142cde82cf/Makefile#L41): `make container ARCH=arm64`

However, this is for a working *Bottlerocket OS* image - there's other changes that we're dependent on to make ARM cluster nodes usable.

* EKS cluster nodes will need to have the [public-preview images and configuration](https://github.com/aws/containers-roadmap/tree/master/preview-programs/eks-arm-preview) setup for the launched instances to manage ENIs attached to them.
* The `pause` image ([`settings.kubernetes.pod-infra-container-image`](https://github.com/bottlerocket-os/bottlerocket#kubernetes-settings)) needs to reference an image that's either built for ARM *or* that has a multiarch manifest defined with an ARM image listed. We can use the EKS preview program repository for ARM that's set in the [EKS image bootstrap script](https://github.com/awslabs/amazon-eks-ami/blob/729dcb5f6dee3428e17c10b46c573c11802e4002/files/bootstrap.sh#L230).

We're tracking [the public roadmap issue regarding ECR's multiarch support](https://github.com/aws/containers-roadmap/issues/505) to address the need for architecture specific `settings.kubernetes.pod-infra-container-image` values (and our other container images). Ideally, we'd have our images built for each architecture, distributed together with a multiarch manifest, and referenced uniformly in `settings.*`.

**Comment by jhaynes** [comment]
ECR now has [multiarch](https://aws.amazon.com/about-aws/whats-new/2020/05/ecr-now-supports-manifest-lists-for-multi-architecture-images/) support!

**Comment by scottmalkie** [comment]
EKS support for Graviton/Graviton2 went GA yesterday! Would be great to have "out of the box" multi-arch support for bottlerocket-based clusters.

**Comment by jahkeup** [comment]
Thanks for checking in! Bottlerocket now has ARM images built and available for use!

The images can be queried from SSM with the method you'd use for `x86_64` images, replacing `x86_64` with `arm64`. For example, to fetch the latest k8s 1.17 image, the parameter name would be:

```
/aws/service/bottlerocket/aws-k8s-1.17/arm64/latest/image_id
```

Please see the [Finding an AMI](https://github.com/bottlerocket-os/bottlerocket/blob/29635e6021a5b8f358d33a4e04ced19258f7f9c0/QUICKSTART.md#finding-an-ami) section of the docs for more details.
