### ISSUE TITLE
relauto: CI builds for PRs failing, missing build/meta output

### ISSUE THREAD

**Issue by jahkeup** [bottlerocket-os/bottlerocket#657]
The PR builds are currently failing because the expected `build/meta` output is missing.

This may be caused by the main build's `cleanup` task or is not written out correctly.

- [x] Identity if its removal from a cleaning task or a bad-write by the script
~~- If task:~~
  - ~~[ ] Update `buildspec` to reorder~~
- If script:
  - [x] Update builder container
  - [x] Push image for use by build projects
